name: update-paratexts
on:
  repository_dispatch:
    types: [trigger-update]
jobs:
  update-paratexts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: |
          npm install jsdom saxon-js
          git clone https://github.com/TST-Project/mss.git scripts/paratexts/mss
          node scripts/paratexts/gethtmlblessings.js
          node scripts/paratexts/getcolophons.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: automatic paratexts update
          file_pattern: scripts/paratexts/*.html
          commit_user_name: TST Bot
