name: update-paratexts
on:
  repository_dispatch:
    types: [trigger-update]
jobs:
  update-paratexts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: |
          npm install jsdom saxon-js
          cd scripts/paratexts
          node gethtmlblessings.js
          node getcolophons.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: automatic paratexts update
          file_pattern: blessings.html colophons.html
          commit_user_name: TST Bot
